version: '3.8'
services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000/api/v1/
    restart: always

networks:
  app-network:
    driver: bridge